### ISSUE TITLE
The package 'react-native-folding-feature' doesn't seem to be linked

### ISSUE THREAD

**Issue by joycelsq84** [logicwind/react-native-fold-detection#6]
hi

now we getting error

 ERROR  Error: The package 'react-native-folding-feature' doesn't seem to be linked. Make sure:

- You rebuilt the app after installing the package
- You are not using Expo Go

This error is located at:
    in FoldingFeatureProvider (at App.js:8)
    in App (at withDevTools.js:18)
    in withDevTools(App) (at renderApplication.js:57)
    in RCTView (at View.js:116)
    in View (at AppContainer.js:127)
    in RCTView (at View.js:116)
    in View (at AppContainer.js:155)
    in AppContainer (at renderApplication.js:50)
    in main(RootComponent) (at renderApplication.js:67), js engine: hermes

**Comment by husenLogicwind** [comment]
@joycelsq84 can you please provide more details.
(1) react native version
(2) expo version
(3) is this issue happening on compile time or run time?

We will soon look into it.
