### ISSUE TITLE
[RN 0.76.0] can't build ios

### ISSUE THREAD

**Issue by eyupdogan** [logicwind/react-native-fold-detection#9]
# Description
'RNFoldDetectionSpec.h' file not found

<img width="753" alt="Screenshot 2024-12-10 at 14 34 58" src="https://github.com/user-attachments/assets/74c51521-3772-4fe4-950d-0b323b600a3a">

**Comment by FrancoTanzarellaEviivo** [comment]
I have the same issue. Using the latest version 0.3.0 with RN 76. Setup react-native.config as per docs.
![Screenshot 2024-12-10 at 09 17 43](https://github.com/user-attachments/assets/c0123717-8a29-42ca-8e5c-3ca1b614adf7)

**Comment by eyupdogan** [comment]
> @eyupdogan : Can you share any screenshot from xcode or teminal error logs Also provide following detail Which version of [react-native-fold-detection](https://github.com/logicwind/react-native-fold-detection) you are using

I added a screenshot and the version is '0.3.0'

**Comment by eyupdogan** [comment]
I fixed this issue by removing if condition
<img width="808" alt="Screenshot 2024-12-10 at 16 53 34" src="https://github.com/user-attachments/assets/b7eb527b-75d3-4380-b66a-6657181ff35e">
